Remove view token link while queueing
tracer-protocol/pools-client pull request #419
Opened 2022-01-13 15:42 UTC by dweberdev

Task 5 of #393 

Issue: 
Bug on the pending toaster when minting a token. The 'view token on Arbiscan' link is broken. Please remove this link all together.
![image](https://user-images.githubusercontent.com/97488700/149361309-1af67b4c-5a30-4395-a970-44ca157db181.png)

No screenshot available since I'm not able to duplicate issue locally

2022-01-17 04:30 UTC, dospore requested changes
lgtm just a couple of unused vars in this file now, should flag it in a lint

2022-01-19 23:20 UTC, dospore requested changes
A couple of conflicts

2022-01-20 17:00 UTC, dweberdev reviewed
Addressed conflict

2022-01-24 07:07 UTC, dospore approved these changes

2022-01-24 22:31 UTC, merged