Pools V2 trade history API
tracer-protocol/pools-client pull request #496
Opened 2022-02-15 13:25 UTC by Steven-Yulong-Yan

Update trade history API

2022-02-15 15:36 UTC, dweberdev commented on archetypes/Portfolio/History/index.tsx
> +    console.log(typeof price);
Remove console.log

2022-02-24 01:49 UTC, ScaredIbis requested changes

2022-02-24 01:49 UTC, ScaredIbis commented on archetypes/Portfolio/History/index.tsx
> +                        {toApproxCurrency((price.toNumber() / 1e18) * (tokenInAmount.toNumber() / 1e18))}
this should use the dynamic value for decimals (`tokenDecimals` on the trade history items)

2022-02-24 01:49 UTC, ScaredIbis commented on archetypes/Portfolio/History/index.tsx
> +                            at {toApproxCurrency(price.toNumber() / 1e18)} USD/token
I have updated the api to return name and symbol of the pricing token, we'll need to replace any hardcoded `USD`'s with this

2022-02-24 01:49 UTC, ScaredIbis commented on archetypes/Portfolio/History/index.tsx
> +                    <TableRowCell>{toApproxCurrency(fee.toNumber() / 1e18)} USDC</TableRowCell>
use dynamic decimals here

2022-02-24 01:49 UTC, ScaredIbis commented on libs/utils/tradeHistoryAPI.ts
> +const BASE_TRADE_HISTORY_API = 'https://dev.api.tracer.finance/poolsv2/tradeHistory';
assume this was a temp change, need to undo it

2022-02-24 01:49 UTC, ScaredIbis commented on libs/utils/tradeHistoryAPI.ts
> +    tokenOutAmount: string;
this type has been updated to include the following fields:

`priceTokenAddress`: string
`priceTokenName`: string
`priceTokenSymbol`: string

2022-02-24 13:57 UTC, dospore commented on archetypes/Portfolio/History/index.tsx
> +                        <div>{(tokenInAmount.toNumber() / 1e18).toFixed(2)} tokens</div>
Dynamic decimals here as well

2022-02-24 13:57 UTC, dospore commented on archetypes/Portfolio/History/index.tsx
> +                        {toApproxCurrency((price.toNumber() / 1e18) * (tokenInAmount.toNumber() / 1e18))}
and here

2022-02-24 13:57 UTC, dospore commented on archetypes/Portfolio/History/index.tsx
> +                            at {toApproxCurrency(price.toNumber() / 1e18)} USD/token
dynamic decimals

2022-02-24 13:57 UTC, dospore commented on archetypes/Portfolio/History/index.tsx
> +                    <TableRowCell>{toApproxCurrency(fee.toNumber() / 1e18)} USDC</TableRowCell>
I dont think this will always be USDC so will have to use `quoteToken.symbol` here as well

2022-03-07 23:35 UTC, dospore approved these changes

2022-03-08 06:59 UTC, ScaredIbis approved these changes

2022-03-08 07:01 UTC, merged