Add parameter data to table in PoolDetailsModal.tsx
tracer-protocol/pools-client pull request #755
Opened 2022-07-12 00:43 UTC by TimJones97

Preview:

![image](https://user-images.githubusercontent.com/19278287/178383757-6485faf1-a9ca-462c-a853-44e75ca70c68.png)

2022-07-12 01:04 UTC, iflp approved these changes, later dismissed
lgtm

2022-07-12 04:50 UTC, ScaredIbis commented
Titles in this modal need theming support. Also for spot price oracles this isn't super applicable. We could consider reducing these two fields (SMA periods and SMA total length) to oracle type and use something similar to https://github.com/tracer-protocol/pools-client/blob/release-v2/utils/pools.ts#L131 to generate the value for it

2022-07-12 07:18 UTC, ScaredIbis requested changes, later dismissed

2022-07-12 07:18 UTC, ScaredIbis commented on archetypes/Pools/PoolDetailsModal/index.tsx
> +                value: pool?.oracle.updateInterval ? formatSeconds(pool?.oracle.updateInterval) : 0,
this should be pool.updateInterval instead

2022-07-15 02:16 UTC, iflp submitted a review, later dismissed

2022-07-15 02:24 UTC, iflp approved these changes

2022-07-15 03:44 UTC, merged