Add fees to Trade modal summary
tracer-protocol/pools-client pull request #758
Opened 2022-07-13 03:03 UTC by TimJones97

https://mycelium-mex.atlassian.net/browse/POOL-83
https://tracerfinance.atlassian.net/browse/DEV-226

Previews:

Mint (changes highlighted in red): 

![image](https://user-images.githubusercontent.com/19278287/178641393-5890b1dd-79e0-4ef7-b52d-a49537a90ee0.png)

Burn:

![image](https://user-images.githubusercontent.com/19278287/178641476-b22c4b2d-0dc7-4eb3-b24c-2069516fd5d6.png)

Flip:

![image](https://user-images.githubusercontent.com/19278287/178641696-a5d7c578-9506-4c4d-9b9b-ba192919a060.png)

Designs:

https://www.figma.com/file/gA9jQ5B6ZwWjGKBhGUFbKo/2.0-3.0-Pools?node-id=2870%3A193085

2022-07-13 04:18 UTC, iflp commented on archetypes/Exchange/Summary/index.tsx
> +                            annualFeePercent={new BigNumber(2)}
Should we be hardcoding the annual fee?

2022-07-13 06:12 UTC, ScaredIbis requested changes, later dismissed

2022-07-13 06:12 UTC, ScaredIbis commented on archetypes/Exchange/Summary/ApproxCommitFee.tsx
>          if (amount.toNumber() === 0) {
this doesn't seem to be getting hit despite fees being 0 (only when there is a value in the amount input)

no value:
![image](https://user-images.githubusercontent.com/14157626/178663018-199da56d-710c-4f7e-8dac-5d21a4276328.png)

with value:
![image](https://user-images.githubusercontent.com/14157626/178663073-9dde084c-8912-441e-aeda-cd722c397107.png)

2022-07-14 05:13 UTC, iflp approved these changes

2022-07-14 05:15 UTC, merged