Allow auto importing Pools from localStorage and URL parameters
tracer-protocol/pools-client pull request #760
Opened 2022-07-14 05:08 UTC by TimJones97

- Stores Pools imported from URL parameters into localStorage variable `importedPools`
- Concatenates existing stored Pool addresses with new addresses obtained from URL parameters
- Auto populates imported Pools into table on Trade page

2022-07-15 02:36 UTC, iflp approved these changes, later dismissed

2022-07-18 07:29 UTC, ScaredIbis requested changes

2022-07-18 07:29 UTC, chrdevmar commented on hooks/useUpdatePoolInstances/index.ts
> +        const isDuplicatePool = poolLists.some((v: StaticPoolInfo) => v.address === address);
not sure if its handled elsewhere but might want to convert to lowercase or something for duplicate check in case a user pastes in a lowercase address which would not be strictly equal to the same checksummed one

2022-07-19 04:14 UTC, ScaredIbis approved these changes
lgtm

2022-07-19 04:15 UTC, merged